name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: module.json
        env:
          version: ${{github.event.release.tag_name}}
          manifest: https://github.com/unrealkakeman89/mandalorian-codex/releases/download/${{github.event.release.tag_name}}/module.json
          download: https://github.com/unrealkakeman89/mandalorian-codex/releases/download/${{github.event.release.tag_name}}/release.zip

      # Create zip file
      - run: zip -r ./release.zip *

      # Substitute tag for changelog
      - name: Substitute tag
        id: substitute_tag
        uses: ashley-taylor/regex-property-action@1.2
        with:
          value: ${{github.event.release.tag_name}}
          regex: "[v.]"
          flags: "g"
          replacement: ""

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Update release with zip file
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./module.json, ./release.zip"
          body: "Changelog: https://github.com/unrealkakeman89/mandalorian-codex/blob/${{github.ref_name}}/CHANGELOG.md#${{steps.substitute_tag.outputs.value}}---${{steps.date.outputs.date}}"
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
